# Generated by Django 3.0.3 on 2020-05-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200524_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
    ]
