# Generated by Django 3.0.3 on 2020-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('articleimg', models.FileField(blank=True, upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='articleimg',
        ),
    ]
