# Generated by Django 3.0.3 on 2020-05-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200524_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleimg',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
